spring:
  application:
    name: demo
  datasource:
    url: jdbc:sqlite:demo-docs.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true