spring:
  application:
    name: demo
  datasource:
    url: jdbc:sqlite:demo-docs.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  secret: very-secret-key-change-this-in-production-please-2026
  access-token-expire-ms: 1800000
  refresh-token-expire-ms: 1209600000
